- How-to-Graph-Your-Network.md
Let's see if we can get this right now.
> Issue 6 how to graph your network

- Documentation-Standards.md
- Viewing-Graphs.md
Adding missing `Table 8-1. Tree Sporting Type Definitions`
> Issue 6 viewing graphs

- User-Management.md
Adding missing Table 9-1. Field Description: User Management
> Issue 6 user management

- Data-Input-Methods.md
> Adding Table 11-1 and Table 11-2

- Data-Queries.md
This is the latest one for this file and I had finally made use of rebase 🐙
> Oh dear, another missing table for the same file. Table 12-4

- Templates.md
> Adding missing Tables 13-1, 13-2, 13-3, 13-4 and 13-5

- RRDTool-Specific-Features.md
Last 2 missing tables. Issue#6 is now on your hands to do what ever you want.
> Adding missing tables 19-1 and 19-2

- Standards-Code-Formatting.md
https://docs.cacti.net/dev_standards:code_formatting#formatting_guidlines
Issue#8 Missing files
> Adding Dev Standards Code Formatting

- Standards-FileSystem-Layout.md
https://docs.cacti.net/dev_standards:file_system_layout
> Issue 8 standards file system layout.md

- Standards-Patch-Creation.md
https://docs.cacti.net/dev_standards:patch_creation
> Issue 7 standards patch creation.md

- Plugin-Creating-Plugins.md
- Plugin-Guidelines.md
- Plugin-Hook-API-Ref.md
- Plugin-Reference.md
- README.md
https://docs.cacti.net/plugins:development.create_new#creating_a_plugin
https://docs.cacti.net/plugins:development.hook_api_ref#hook_api_reference
https://docs.cacti.net/plugins:development.reference_plugin
https://docs.cacti.net/plugins.guidelines
> Issue 7 plugin related files

- Plugin-Creating-Plugins.md
- Plugin-Reference.md
- Standards-Code-Formatting.md
- Standards-FileSystem-Layout.md
> Changed a couple of fenced codes from markdown to console.

- Install-Under-CentOS_LAMP.md
- Install-Under-CentOS_LEMP.md
- README.md
Includes LAMP and LEMP stack instructions.
> Installation instructions for CentOS 7

- Install-Under-CentOS_LEMP.md
Forgot to clean up nginx config file. This is the working config without all unsed statements.
> Nginx config clean and tidy up

- General-Installing-Instructions.md
- Upgrading-Cacti-Under-FreeBSD.md
There is a lot obsolete information about FreeBSD. I made little update.
> Update FreeBSD installation process

- Update How-To-Setup-Remote-Pollers.md
inital document in repo on Remote poller setup
> Create Update How-To-Setup-Remote-Pollers.md

- Install-Under-CentOS_LAMP.md
a few of the lines with code samples weren't quite indented enough, I just got them all to line up so the page looks as intended, hopefully this helps!
> Corrected very minor formatting errors

- Install-Under-CentOS_LAMP.md
replace nginx by apache for cron task configuration;
Split "GRANT ALL" to two SQL "CREATE USER" and "GRANT ALL" for MySQL 8
> two fixing form LAMP installation guide

- Plugin-Hook-API-Ref.md
Add permission_denied.php to hook custom_denied filelist (Cacti/cacti#2426)
> Add permission_denied.php to hook custom_denied filelist

- Devices.md
- Plugins.md
> image fixes
